# .github/workflows/nodejs-install.yml
name: Node.js Install and Dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker: [1, 2, 3, 4, 5] # Define a matrix of 5 workers

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify Node.js version here

      - name: Install dependencies
        run: npm install bip39 bip32 bs58 tiny-secp256k1 elliptic

      - name: Run main.js script
        run: node main.js turjaun
        
